spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ENC(SdZkvRsnek+3Hh6LzG0QOw==)
    url: ENC(ChqJ4sM/ZUKRGzq696YMz78SWVMRpTWS0LVBF975Z/kVO+vpkQiFV3CmuD+gff1xPQ1A7GJolXx1dgNMxKriHUyPD1FCSd4k/yjMWSkHQhNNpxMuq03bpA==)
    password: ENC(l26SgFG5yPvqqlL6dLI2LA==)
  jpa:
    hibernate:
      ddl-auto: update
jwt:
  secret:
    key: ENC(BCTdm+KRfD8KK13KY6Gi3mnlIC+xJkJFrwGTRvkLQ1F9RmmAPkHk71u6T2g+g2jts+SiuOO8BGiK9WdQT56zdTRzEkynvhcQnhWh9cIqytMiPuBsWqx12y2jB/7lu9rYuIs5MfFrR8A4il5WlSL4zIjaujDBNGsFQfnfNrjfgV8qJReGMzGA6g==)

jasypt:
  encryptor:
    property:
      prefix: ENC(
      suffix: )
    algorithm: PBEWithMD5AndDES
    iv-generator-classname: org.jasypt.iv.NoIvGenerator
    bean: jasyptStringEncryptor
    password: 230809
