spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ENC(SdZkvRsnek+3Hh6LzG0QOw==)
    url: ENC(ChqJ4sM/ZUKRGzq696YMz78SWVMRpTWS0LVBF975Z/kVO+vpkQiFV3CmuD+gff1xPQ1A7GJolXx1dgNMxKriHUyPD1FCSd4k/yjMWSkHQhNNpxMuq03bpA==)
    password: ENC(l26SgFG5yPvqqlL6dLI2LA==)
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
  data:
    redis:
      host: 127.0.0.1
      port: 6379
jwt:
  secret:
    key: ENC(BCTdm+KRfD8KK13KY6Gi3mnlIC+xJkJFrwGTRvkLQ1F9RmmAPkHk71u6T2g+g2jts+SiuOO8BGiK9WdQT56zdTRzEkynvhcQnhWh9cIqytMiPuBsWqx12y2jB/7lu9rYuIs5MfFrR8A4il5WlSL4zIjaujDBNGsFQfnfNrjfgV8qJReGMzGA6g==)

jasypt:
  encryptor:
    property:
      prefix: ENC(
      suffix: )
      bean: jasyptStringEncryptor
      password: ENC(ykR6sevQXU/gYFcNEx/Vqw==)

naver-cloud:
  accessKey : ENC(TAB/kxScJwa0mF/LbXIZ2ak9iAaSbMJOjUJKnQNrWkY=)
  secretKey : ENC(geSn12XqZFmmSxYr0FlgxISkHz+ZX+E20D5SB55PCR0oawTthPZYroMQGm3fJgqaQdi3nuV6jQw=)
  sms:
    serviceId : ENC(EVyAot+A6ow1ZtJG/dXT/rMxE6i8bJhiBKn6Vllt5ov928/a/zqmbrpIgmIPbTJp)
    senderPhone : "01000000000"
  s3:
    end-point: "https://kr.object.ncloudstorage.com"
    region-name: "kr-standard"
java-mail:
  hostname: ENC(EPeQgROSy1+/Ev6pMXGeYea5cwMwRQlX)
  identifier: ENC(Hfd5ajAKGVf9PldJtig0JQ==)
  password: ENC(dJIuacH5gbfOZHlDDHJkVfZMHaRdXLIa)
  port: ENC(T4AuzQ7+K9X0O3rHuBQieA==)



